apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
    role: monitoring
    infra: backend
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: node-exporter
      port: 9100
      protocol: TCP
  selector:
    app: node-exporter
    role: monitoring
    infra: backend
