apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pulseaudio
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pulseaudio
    spec:
      containers:
      - name: pulseaudio
        image: jess/pulseaudio
        # image: debian
        # command:
        # - "/bin/bash"
        # - "-xc"
        # - >
        #   apt-get update;
        #   apt-get install -y --no-install-recommends pulseaudio;
        #   pulseaudio --system --disallow-exit --disallow-module-loading
        imagePullPolicy: Always
        ports:
        - name: test
          containerPort: 4317
        - name: simple
          containerPort: 4711
        - name: cli
          containerPort: 4712
        - name: native
          containerPort: 4713
        - name: http
          containerPort: 4714
        - name: rtp-tcp
          protocol: TCP
          containerPort: 5004
        - name: rtp-udp
          protocol: UDP
          containerPort: 5004
        # readinessProbe:
        #   tcpSocket:
        #     port: 5004
        #   failureThreshold: 1
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 2
        # livenessProbe:
        #   tcpSocket:
        #     port: 5004
        #   failureThreshold: 3
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 2
        volumeMounts:
        - name: current-config
          mountPath: /etc/pulse
      volumes:
      - name: current-config
        configMap:
          name: config.general.pulseaudio
