---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-drone
  namespace: drone
spec:
  # storageClassName: gold
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
