apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-07-16T09:47:34Z
  generation: 1
  labels:
    app: drone
    chart: drone-1.4.0
    component: agent
    heritage: Tiller
    release: drone
  name: drone-drone-agent
  namespace: default
  resourceVersion: "2582"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/drone-drone-agent
  uid: 44115534-88dd-11e8-a0c0-080027ccfeda
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: drone
      component: agent
      release: drone
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/secrets: de51946e41fb34ced4691027c69502f0ae166d442c5fe05e18eea919ac3543fa
      creationTimestamp: null
      labels:
        app: drone
        component: agent
        release: drone
    spec:
      containers:
      - env:
        - name: DRONE_SERVER
          value: drone-drone:9000
        - name: DRONE_SECRET
          valueFrom:
            secretKeyRef:
              key: secret
              name: drone-drone
        - name: DRONE_DEBUG
          value: "false"
        image: docker.io/drone/agent:0.8.5
        imagePullPolicy: IfNotPresent
        name: drone-drone-agent
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 40m
            memory: 32Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: drone-drone
      serviceAccountName: drone-drone
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: docker-socket
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-07-16T09:47:34Z
    lastUpdateTime: 2018-07-16T09:47:34Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-07-16T09:47:34Z
    lastUpdateTime: 2018-07-16T09:47:36Z
    message: ReplicaSet "drone-drone-agent-5f7c95d4bf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
