apiVersion: v1
kind: Service
metadata:
  labels:
    app: drone
    chart: drone-1.4.0
    heritage: Tiller
    release: drone
  name: drone-drone
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: grpc
    port: 9000
  selector:
    app: drone
    component: server
    release: drone
