apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: 2018-07-16T09:47:34Z
  labels:
    app: drone
    chart: drone-1.4.0
    heritage: Tiller
    release: drone
  name: drone-drone
  namespace: default
  resourceVersion: "2534"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/default/rolebindings/drone-drone
  uid: 440dca75-88dd-11e8-a0c0-080027ccfeda
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: drone-drone
subjects:
- kind: ServiceAccount
  name: drone-drone
  namespace: default
apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: 2018-07-16T09:47:34Z
    labels:
      app: drone
      chart: drone-1.4.0
      heritage: Tiller
      release: drone
    name: drone-drone
    namespace: default
    resourceVersion: "2531"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/default/roles/drone-drone
    uid: 440ce098-88dd-11e8-a0c0-080027ccfeda
  rules:
  - apiGroups:
    - extensions
    resources:
    - deployments
    verbs:
    - get
    - list
    - patch
    - update
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
