apiVersion: v1
kind: Service
  name: alertmanager
  namespace: monitoring
metadata:
  labels:
    name: alertmanager
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
spec:
  type: NodePort
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
  selector:
    app: alertmanager
