apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  labels:
    app: alertmanager
spec:
  ports:
  - name: http
    port: 9093
    protocol: TCP
    targetPort: 9093
  - name: meshpeer
    port: 6783
    protocol: TCP
    targetPort: 6783
  selector:
    app: alertmanager
