---
apiVersion: v1
kind: Secret
metadata:
  name: secret.general.rabbitmq
type: Opaque
data:
  rabbitmq.pwd: YjJ3U0RBUXNKZW9MNXl1OHlFQ1RHRg==
  rabbitmq.cookie: ekEyZG9aRmpvSkJhN2p0WERXNnhSWlNHM1Bh
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config.general.rabbitmq
data:
  rabbitmq.user: octer
  rabbitmq.plugins: |
    [autocluster].
  rabbitmq.config: |
    [
      { rabbit,
        [
          { loopback_users, [ ] }
        ]
      },
      {
        rabbitmq_management,
          [
            {load_definitions, "/etc/rabbitmq/definitions.json"}
          ]
      }
    ].
  rabbitmq.definitions: |
    {
       "rabbit_version":"3.6.5",
       "users":[
          {
             "name":"guest",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":"administrator"
          },
          {
             "name":"comms-processor",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          },
          {
             "name":"feed-downloader",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          },
          {
             "name":"feed-scheduler",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          },
          {
             "name":"image-processor",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          },
          {
             "name":"index-cloner",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          },
          {
             "name":"logstash",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          },
          {
             "name":"misc-indexer",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          },
          {
             "name":"product-categorizer",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          },
          {
             "name":"product-cleaner",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          },
          {
             "name":"product-connector",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          },
          {
             "name":"product-deduper",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          },
          {
             "name":"product-flag-processor",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          },
          {
             "name":"product-grouper",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          },
          {
             "name":"product-indexer",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          },
          {
             "name":"product-labeler",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          },
          {
             "name":"product-slugger",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          },
          {
             "name":"product-sorter",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          },
          {
             "name":"product-subgrouper",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          },
          {
             "name":"backoffice",
             "password_hash":"imvdwUigPiDKxyUbxAf3JW2cKS2N7FR1uMMjEeaSRyPoM5zk",
             "hashing_algorithm":"rabbit_password_hashing_sha256",
             "tags":""
          }
       ],
       "vhosts":[
          {
             "name":"/"
          },
          {
             "name":"comms"
          },
          {
             "name":"product"
          }
       ],
       "permissions":[
          {
             "user":"guest",
             "vhost":"/",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"guest",
             "vhost":"comms",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"guest",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"comms-processor",
             "vhost":"comms",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"feed-downloader",
             "vhost":"comms",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"feed-scheduler",
             "vhost":"comms",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"index-cloner",
             "vhost":"comms",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"feed-downloader",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"feed-scheduler",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"image-processor",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"index-cloner",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"logstash",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"misc-indexer",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"product-categorizer",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"product-cleaner",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"product-connector",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"product-deduper",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"product-flag-processor",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"product-grouper",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"product-indexer",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"product-labeler",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"product-slugger",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"product-sorter",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"product-subgrouper",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          },
          {
             "user":"backoffice",
             "vhost":"product",
             "configure":".*",
             "write":".*",
             "read":".*"
          }
       ],
       "parameters":[

       ],
       "policies":[

       ],
       "exchanges":[
          {
             "name":"comms",
             "vhost":"comms",
             "type":"direct",
             "durable":true,
             "auto_delete":false,
             "internal":false,
             "arguments":{

             }
          },
          {
             "name":"feed",
             "vhost":"product",
             "type":"direct",
             "durable":true,
             "auto_delete":false,
             "internal":false,
             "arguments":{

             }
          },
          {
             "name":"document",
             "vhost":"product",
             "type":"direct",
             "durable":true,
             "auto_delete":false,
             "internal":false,
             "arguments":{

             }
          },
          {
             "name":"label",
             "vhost":"product",
             "type":"direct",
             "durable":true,
             "auto_delete":false,
             "internal":false,
             "arguments":{

             }
          },
          {
             "name":"category",
             "vhost":"product",
             "type":"direct",
             "durable":true,
             "auto_delete":false,
             "internal":false,
             "arguments":{

             }
          },
          {
             "name":"nonproduct",
             "vhost":"product",
             "type":"direct",
             "durable":true,
             "auto_delete":false,
             "internal":false,
             "arguments":{

             }
          },
          {
             "name":"store",
             "vhost":"product",
             "type":"direct",
             "durable":true,
             "auto_delete":false,
             "internal":false,
             "arguments":{

             }
          },
          {
             "name":"product",
             "vhost":"product",
             "type":"direct",
             "durable":true,
             "auto_delete":false,
             "internal":false,
             "arguments":{

             }
          },
          {
             "name":"group",
             "vhost":"product",
             "type":"direct",
             "durable":true,
             "auto_delete":false,
             "internal":false,
             "arguments":{

             }
          },
          {
             "name":"servicedefinition",
             "vhost":"product",
             "type":"direct",
             "durable":true,
             "auto_delete":false,
             "internal":false,
             "arguments":{

             }
          },
          {
             "name":"price",
             "vhost":"product",
             "type":"direct",
             "durable":true,
             "auto_delete":false,
             "internal":false,
             "arguments":{

             }
          }
       ]
    }
