apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  clusterIP: None
  ports:
  - name: amqp-1
    port: 5671
  - name: amqp-2
    port: 5672
  - name: epmd
    port: 4369
  - name: rabbitmq-dist
    port: 25672
  - name: http
    port: 15672
  selector:
    app: rabbitmq
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  labels:
    app: rabbitmq
  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: "9090"
spec:
  ports:
  - name: http
    port: 15672
  - name: exporter
    port: 9090
  selector:
    # component: rabbitmq-management
    app: rabbitmq
  type: NodePort
