---
apiVersion: v1
kind: Secret
metadata:
  name: rocketchat-config
  labels:
    app: rocketchat
type: Opaque
data:
  mail-url: "" # {{ printf "smtp://%s:%s@%s:%s" .Values.config.SMTP_Username .Values.config.SMTP_Password .Values.config.SMTP_Host .Values.config.SMTP_Port | b64enc | quote }}
  mongo-uri: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvcm9ja2VyY2hhdAo=
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-config
  labels:
    app: mongodb
type: Opaque
data:
  mongodb-root-password: cGFzc3dvcmQK
  mongodb-password: cGFzc3dvcmQK
