apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calibre
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: calibre
    spec:
      containers:
      - name: server
        # image: debian
        # command:
        # - /bin/sh
        # - -c
        # - >
        #   sleep infinity;
        image: regueiro/calibre-server:latest
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - >
          sleep infinity;
        # args:
        # - "--listen-on=0.0.0.0"
        # - "--enable-local-write"
        # - "--enable-log-not-found"
        # - "--url-prefix=/Books"
        # - "--log=/dev/stderr"
        # - "--access-log=/dev/stdout"
        # - "--userdb"
        # - "/root/.config/calibre/server-users.sqlite"
        # - "--enable-auth"
        # - "/opt/calibre/library"
        # # env:
        # # - name: LANG
        # #   value: fr_FR
        ports:
        - name: calibre
          containerPort: 8080
        volumeMounts:
        - name: calibre
          mountPath: /root/.config/calibre/
          subPath: docker/calibre
        - name: calibre
          mountPath: /opt/calibre/library
          subPath: Ebooks/Library
        - name: calibre
          mountPath: /download
          subPath: downloads/Books
      # - name: auto-add
      #   image: regueiro/calibre-server:latest
      #   imagePullPolicy: Always
      #   command:
      #   - "/bin/bash"
      #   - "-c"
      #   - >
      #     calibredb add /download/ -r --with-library=http://calibre:8080/Books/
      #   volumeMounts:
      #   - name: calibre
      #     mountPath: /download
      #     subPath: downloads/Books
      volumes:
      - name: calibre
        glusterfs:
          endpoints: glusterfs-cluster
          path: data
          readOnly: false
