apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: calibre
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.passHostHeader: "true"
    traefik.backend.loadbalancer.stickey: "true"
    # traefik.ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
  - host: file.leangeder.eu
    http:
      paths:
      - path: /Books/
      # - path: /
        backend:
          serviceName: calibre
          servicePort: http
