apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    component: core
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
        component: core
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        # image: prom/prometheus:v1.7.0
        image: prom/prometheus
        args:
          # - '-storage.local.retention=24h'
          # - '-storage.local.series-file-shrink-ratio=0.3'
          - '-storage.local.retention=360h'
          - '-storage.local.memory-chunks=1048576'
          - '-config.file=/etc/prometheus/prometheus.yaml'
          - '-alertmanager.url=http://alertmanager:9093/alertmanager'
        ports:
        - name: webui
          containerPort: 9090
#         resources:
#           requests:
#             cpu: 100m
#             memory: 100M
#           limits:
#             cpu: 500m
#             memory: 2500M
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: rules-volume
          mountPath: /etc/prometheus-rules
        - name: prometheus-data
          mountPath: /prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-core
      - name: rules-volume
        configMap:
          name: prometheus-rules
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus-data
