---
apiVersion: v1
kind: Service
metadata:
  name: varnish
  labels:
    app: varnish
spec:
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  externalIPs:
  - 62.210.14.17
  selector:
    app: varnish
