---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "DEBUG"
    # defaultEntryPoints = ["http","https"]
    defaultEntryPoints = ["http"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
    #   [entryPoints.http.redirect]
    #   entryPoint = "https"
    #   # [entryPoints.https.auth.basic]
    #   # users = ["leangeder:$apr1$k2qslCn6$0OgA8vhnyC8nJ99YfJMOM/"]
    #   [entryPoints.https]
    #   address = ":443"
    #   [entryPoints.https.tls]

    [kubernetes]

    [web]
      [web.statistics]
      RecentErrors = 100

    [web.metrics.prometheus]
      Buckets = [0.1,0.3,1.2,5.0]

    # [acme]
    # email = "40153@supinfo.com"
    # storage = "/acme/acme.json"
    # entryPoint = "https"
    # onHostRule = true
    # [[acme.domains]]
    # main = "leangeder.eu"
    # sans = ["movie.leangeder.eu", "serie.leangeder.eu", "nzb.leangeder.eu", "book.leangeder.eu", "music.leangeder.eu"]
    # [acme.httpChallenge]
    #   entryPoint = "http"
