apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: book
  annotations:
    kubernetes.io/ingress.class: "traefik"
    # traefik.frontend.passHostHeader: "true"
    # traefik.backend.loadbalancer.stickey: "true"
    # ingress.kubernetes.io/rewrite-target: "/ubooquity"
spec:
  rules:
  - host: book.leangeder.eu
    http:
      paths:
      - path: /
        backend:
          serviceName: book
          servicePort: http
      - path: /ubooquity/admin
        backend:
          serviceName: book
          servicePort: admin
