---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: syncthing
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      containers:
      - name: syncthing
        image: syncthing/syncthing
        imagePullPolicy: Always
        ports:
        - containerPort: 8384
        - containerPort: 22000
        - containerPort: 21027
        volumeMounts:
        - name: syncthing
          mountPath: /config
          subPath: docker/syncthing
        - name: syncthing
          mountPath: /var/syncthing
          subPath: Others/syncthing
        - name: syncthing
          mountPath: /Others
          subPath: Others
        - name: syncthing
          mountPath: /Movies
          subPath: Movies
        - name: syncthing
          mountPath: /Series
          subPath: Series
        - name: syncthing
          mountPath: /Music
          subPath: Music
        - name: syncthing
          mountPath: /Books
          subPath: Ebooks/Books
        - name: syncthing
          mountPath: /Comics
          subPath: Ebooks/Comics
        - name: syncthing
          mountPath: /Files
          subPath: Ebooks/Files
      volumes:
      - name: syncthing
        glusterfs:
          endpoints: glusterfs-cluster
          path: data
          readOnly: false
