apiVersion: v1
kind: Service
metadata:
  name: syncthing
  labels:
    app: syncthing
spec:
  ports:
  - name: server
    port: 22000
  - name: discover
    port: 21027
  selector:
    app: syncthing
  externalIPs:
  - 62.210.14.17
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-ui
  labels:
    app: syncthing
spec:
  ports:
  - name: http
    port: 8384
  selector:
    app: syncthing
